### ISSUE TITLE
Compiling the CmakeLists.txt file and generating the .so file

### ISSUE THREAD

**Issue by addy1997** [FloodShao/crowd_simulation#13]
Hi @FloodShao, this is a really interesting work. I just wanted to ask you about how you generated this file [CmakeLists.txt](https://github.com/FloodShao/crowd_simulation/blob/master/crowd_simulation_ign/CMakeLists.txt)? I mean what is the procedure to generate CmakeLists.txt for ignition plugins? Also, how do you generate the .so files required to load the ignition plugins? 

Thanks,

**Comment by FloodShao** [comment]
Hi, first of all, this repo might be outdated, so you might need to check `[rmf_demos](https://github.com/osrf/rmf_demos)` for the updated version. 
Besides, the ignition lib (the .so files you mentioned) are actually compiled in separated files. So in your workspace, you should have multiple repos cloned (for developers, the ignition repos as well). I think the updated repos list can be found in [rmf_demos.repos](https://github.com/osrf/rmf_demos/blob/master/rmf_demos.repos). So as you mentioned, each repo has its own CMakelists to generated the .so lib. So in your own repo, as the plugin repo, the only thing you need to do is to guide the CMakeLists to find the .so have already built, which is by setting the Environment variables. This is not hard to do, as the ROS projects are using CMake all the time. 
In all, to generate the CMakelists, first, you have to find out the headers you quote in your source code, and locate the relavant headers and libs you need. And then, you will have to set the Environment variables (in rmf_demos, this is written in a script when you initialize the workspace). And then, you can just use `include_directories` and `link_libraries` to get your plugin.so compiled.
